/**
 * Semantic Cache Repository (MongoDB Atlas Vector Search)
 * 
 * Provides a vector-similarity cache layer for the chat API route,
 * backed by native MongoDB $vectorSearch against the `semantic_cache`
 * collection. Replaces the previous Upstash Vector implementation.
 * 
 * Before running the expensive RAG pipeline + LLM generation, the
 * route embeds the user query and checks this cache for a semantically
 * similar past query whose answer can be replayed.
 * 
 * Design decisions:
 *   - Uses the global MongoDB client singleton (same as all other repos)
 *   - Gracefully degrades: all errors are caught and logged,
 *     never bubbling up to break the normal pipeline
 *   - Relies on a database-level TTL index on `createdAt` for expiry
 * 
 * @module infrastructure/database/cache-repository
 */

import { getDatabase } from './mongodb-client';
import {
  SEMANTIC_CACHE_COLLECTION,
  SEMANTIC_CACHE_VECTOR_INDEX,
  SEMANTIC_CACHE_HIT_THRESHOLD,
  VECTOR_FIELD_PATH,
  VECTOR_NUM_CANDIDATES,
} from '@/config/constants';
import { createLogger } from '@/lib/logger';
import { Document } from 'mongodb';

const log = createLogger('SemanticCache');

// ─── Types ──────────────────────────────────────────────────────────────────

/** Schema of a document in the `semantic_cache` collection */
export interface SemanticCacheDocument {
  /** The original user query text */
  queryText: string;
  /** The embedding vector of the query (2048-dimensional) */
  embedding: number[];
  /** The full assistant answer text */
  answerText: string;
  /** Timestamp for TTL-based expiry at the database level */
  createdAt: Date;
}

/** Returned when a semantically similar cached answer is found */
export interface CacheHit {
  hit: true;
  answer: string;
  score: number;
}

/** Returned when no cached answer meets the similarity threshold */
export interface CacheMiss {
  hit: false;
}

export type CacheResult = CacheHit | CacheMiss;

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Checks the semantic cache for a query whose embedding is
 * sufficiently similar (≥ SEMANTIC_CACHE_HIT_THRESHOLD) to the
 * provided query embedding.
 * 
 * Uses MongoDB Atlas $vectorSearch aggregation against the
 * `semantic_cache` collection, then filters results by the
 * strict 0.95 similarity threshold.
 * 
 * @param queryEmbedding - The embedding vector of the user's query
 *                         (generated by NvidiaClient)
 * @returns CacheHit with the cached answer, or CacheMiss
 */
export async function checkCache(queryEmbedding: number[]): Promise<CacheResult> {
  try {
    const db = await getDatabase();
    const collection = db.collection<SemanticCacheDocument>(SEMANTIC_CACHE_COLLECTION);

    const pipeline: Document[] = [
      {
        $vectorSearch: {
          index: SEMANTIC_CACHE_VECTOR_INDEX,
          path: VECTOR_FIELD_PATH,
          queryVector: queryEmbedding,
          numCandidates: VECTOR_NUM_CANDIDATES,
          limit: 1,
        },
      },
      {
        $project: {
          _id: 0,
          answerText: 1,
          score: { $meta: 'vectorSearchScore' },
        },
      },
    ];

    const results = await collection.aggregate<{ answerText: string; score: number }>(pipeline).toArray();

    if (results.length === 0) {
      log.debug('Semantic cache: no results returned');
      return { hit: false };
    }

    const top = results[0];

    log.info('Semantic cache query result', {
      score: top.score.toFixed(4),
      threshold: SEMANTIC_CACHE_HIT_THRESHOLD,
      isHit: top.score >= SEMANTIC_CACHE_HIT_THRESHOLD,
    });

    if (top.score >= SEMANTIC_CACHE_HIT_THRESHOLD && top.answerText) {
      return {
        hit: true,
        answer: top.answerText,
        score: top.score,
      };
    }

    return { hit: false };
  } catch (error) {
    // Never let cache errors break the main pipeline
    log.error('Semantic cache check failed', {
      error: (error as Error).message,
    });
    return { hit: false };
  }
}

/**
 * Saves a query, its embedding, and the corresponding answer to
 * the semantic cache for future retrieval.
 * 
 * This function is designed to be called in a fire-and-forget
 * manner (non-blocking). It catches its own errors internally.
 * 
 * The `createdAt` field enables database-level TTL index expiry.
 * 
 * @param queryText - The original user query text
 * @param queryEmbedding - The embedding vector of the user's query
 * @param answerText - The full assistant response text to cache
 */
export async function saveToCache(
  queryText: string,
  queryEmbedding: number[],
  answerText: string
): Promise<void> {
  try {
    const db = await getDatabase();
    const collection = db.collection<SemanticCacheDocument>(SEMANTIC_CACHE_COLLECTION);

    const doc: SemanticCacheDocument = {
      queryText,
      embedding: queryEmbedding,
      answerText,
      createdAt: new Date(),
    };

    await collection.insertOne(doc);

    log.info('Semantic cache entry saved', {
      queryLength: queryText.length,
      answerLength: answerText.length,
    });
  } catch (error) {
    // Fire-and-forget safe — log and swallow
    log.error('Semantic cache save failed', {
      error: (error as Error).message,
    });
  }
}
